parameters:
#    front_user.example.class: Front\UserBundle\Example

services:
#    front_user.example:
#        class: %front_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]

    user.form.profile.type:
        class: Front\UserBundle\Form\Type\ProfileType
        parent: fos_user.profile.form.type
        tags:
            - { name: form.type, alias: fos_user_profile }

    user.form.register.type:
        class: Front\UserBundle\Form\Type\RegisterType
        parent: fos_user.registration.form.type
        tags:
            - { name: form.type, alias: fos_user_register }
